### ISSUE TITLE
Usage with scale other than modular-scale

### ISSUE THREAD

**Issue by Madebym** [pyrsmk/vertical-rhythmic#3]
Hi, I would like to combine vertical-rhythmic with some other modular-scale than the one provided in your docs.

The one I am looking at is https://github.com/nickpfisterer/harmon  Basically it is very similar to the one by Team-Sass, just a little more stripped down and easier to use.

Since I am newbie to Sass, is there a way to use it with vertical-rhythmic, like you did with modular-scale ?

**Comment by pyrsmk** [comment]
In fact, I think I should update the docs since vertical-rhythmic and modular-scale fulfill the "same" behavior. You should use one or the other but the both together seems useless and especially not really flexible. But you can use vertical-rhythmic on one side, and modular-scale on the other side.

I explain. Vertical-rhythmic is designed to keep a scale across the typography. Modular-scale keeps a scale based on a natural known ratio. So you can use vertical-rhythmic for the fonts, and modular-scale for your blocks.

Anyway! Harmon is the same library as vertical-rhythmic. Pick the one you love ;)

**Comment by pyrsmk** [comment]
One last note : you can use vertical-rhythmic for typography or blocks, like modular-scale and harmon too. So it's really a matter of taste.

**Comment by pyrsmk** [comment]
The difference is in the baseline creation. Harmon only set the font-size for the baseline, apparently. Vertical-rhythmic sets the font-size, the line-height, and computes a ratio to apply when `vr()` is called. It seems more accurate to me. But you don't have a golden ratio or whatsoever.

**Comment by Madebym** [comment]
@pyrsmk Thanks for the explanation! 

Although, I musr admit, you got me a bit confused now. You say that Harmon and your library are the same thing, I am no expert, but modular scale and vertical rhythm are two completely different things.

Harmon only helps with choosing different font-sizes from pre-defined values + applying line heights.

I was thinking of using your library for consistent vertical rhythm and Harmon for choosing font sizes from various scales.

**Comment by pyrsmk** [comment]
They are different but we can use all of them to accomplish the same thing, as far as I can see. Vertical-rhythmic applies values for font-size and line-height, Harmon too, and modular-scale can be used that way to.
But you're right, with vertical-rhythmic it's more consistent because of its baseline and the ratio he's computing from it.
I just encourage you to choose only one library if possible, because it's becoming too complex to me, otherwise.
